server:
  port: 8090
    
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}
      - id: accountTransaction-service
        uri: lb://accountTransaction-service
        predicates:
        - Path=/transaction/**
        filters:
        - RewritePath=/transaction/(?<path>.*), /$\{path}
      - id: sidecar
        uri: lb://sidecar-service
        predicates:
          - Path=/status/**
        filters:
          - RewritePath=/status/(?<path>.*), /$\{path}